# generated
name: xxlb6nmulgi
on:
  workflow_dispatch: {}
  workflow_call:
    secrets:
      x2tog4huplt:
        required: true
      x62mffq6fec:
        required: true
      xaqnb4spokw:
        required: true
      xbucws5r6z7:
        required: true
      xfvt4ipssxd:
        required: true
      xhnuatecbvz:
        required: true
      xhzquij5vjz:
        required: true
      xkxmguw6k42:
        required: true
      xkz7gzyz75s:
        required: true
      xquqiaiupja:
        required: true
      xrecw4v2j5j:
        required: true
      xwfcb4ka6lh:
        required: true
      xzeifyyht7x:
        required: true
permissions: {}
jobs:
  xt4jcw5tofl:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    outputs:
      x5hwd6xg2qe: ${{ steps.run.outputs.x5hwd6xg2qe }}
      x7y4v67pmx7: ${{ steps.run.outputs.x7y4v67pmx7 }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xchkgycsivv: ${{ secrets.xrecw4v2j5j }}
          xvyp42dr72k: ${{ secrets.xaqnb4spokw }}
          xszotgv4ip5: ${{ secrets.xkz7gzyz75s }}
          xjvh6hrq6ho: xn5647chkxv
          xbtsnkhpgcb: x5hwd6xg2qe,x7y4v67pmx7
          xdq5fsig6vb: ${{ secrets.xkxmguw6k42 }}
          x4xozvrszke: ${{ secrets.xfvt4ipssxd }}
          x3kuchgpu5q: ${{ secrets.xquqiaiupja }}
          xojbojpm6qb: ${{ secrets.xzeifyyht7x }}
          x5p326pvqs3: ${{ secrets.xbucws5r6z7 }}
          x4g2hmsuysm: ${{ secrets.xhzquij5vjz }}
        run: ./.github/bin/xxlb6nmulgi
  x47zqhb2snl:
    uses: ./.github/workflows/xtc3b63konn.yml
    permissions:
      contents: read
      id-token: write
    secrets:
      x2tog4huplt: ${{ secrets.x2tog4huplt }}
      x62mffq6fec: ${{ secrets.x62mffq6fec }}
      xaqnb4spokw: ${{ secrets.xaqnb4spokw }}
      xbucws5r6z7: ${{ secrets.xbucws5r6z7 }}
      xfvt4ipssxd: ${{ secrets.xfvt4ipssxd }}
      xhnuatecbvz: ${{ secrets.xhnuatecbvz }}
      xhzquij5vjz: ${{ secrets.xhzquij5vjz }}
      xkxmguw6k42: ${{ secrets.xkxmguw6k42 }}
      xkz7gzyz75s: ${{ secrets.xkz7gzyz75s }}
      xquqiaiupja: ${{ secrets.xquqiaiupja }}
      xrecw4v2j5j: ${{ secrets.xrecw4v2j5j }}
      xwfcb4ka6lh: ${{ secrets.xwfcb4ka6lh }}
      xzeifyyht7x: ${{ secrets.xzeifyyht7x }}
  xee755g3umz:
    uses: ./.github/workflows/x6g4vtsrqhw.yml
    permissions:
      contents: read
      id-token: write
    secrets:
      x2tog4huplt: ${{ secrets.x2tog4huplt }}
      x62mffq6fec: ${{ secrets.x62mffq6fec }}
      xaqnb4spokw: ${{ secrets.xaqnb4spokw }}
      xbucws5r6z7: ${{ secrets.xbucws5r6z7 }}
      xfvt4ipssxd: ${{ secrets.xfvt4ipssxd }}
      xhnuatecbvz: ${{ secrets.xhnuatecbvz }}
      xhzquij5vjz: ${{ secrets.xhzquij5vjz }}
      xkxmguw6k42: ${{ secrets.xkxmguw6k42 }}
      xkz7gzyz75s: ${{ secrets.xkz7gzyz75s }}
      xquqiaiupja: ${{ secrets.xquqiaiupja }}
      xrecw4v2j5j: ${{ secrets.xrecw4v2j5j }}
      xwfcb4ka6lh: ${{ secrets.xwfcb4ka6lh }}
      xzeifyyht7x: ${{ secrets.xzeifyyht7x }}
  xzo62xy2scr:
    uses: ./.github/workflows/xgrwdzapho4.yml
    permissions:
      contents: read
      id-token: write
    secrets:
      x2tog4huplt: ${{ secrets.x2tog4huplt }}
      x62mffq6fec: ${{ secrets.x62mffq6fec }}
      xaqnb4spokw: ${{ secrets.xaqnb4spokw }}
      xbucws5r6z7: ${{ secrets.xbucws5r6z7 }}
      xfvt4ipssxd: ${{ secrets.xfvt4ipssxd }}
      xhnuatecbvz: ${{ secrets.xhnuatecbvz }}
      xhzquij5vjz: ${{ secrets.xhzquij5vjz }}
      xkxmguw6k42: ${{ secrets.xkxmguw6k42 }}
      xkz7gzyz75s: ${{ secrets.xkz7gzyz75s }}
      xquqiaiupja: ${{ secrets.xquqiaiupja }}
      xrecw4v2j5j: ${{ secrets.xrecw4v2j5j }}
      xwfcb4ka6lh: ${{ secrets.xwfcb4ka6lh }}
      xzeifyyht7x: ${{ secrets.xzeifyyht7x }}
  xtodkjhlfaf:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x47zqhb2snl
      - xee755g3umz
      - xzo62xy2scr
      - xt4jcw5tofl
    outputs:
      xehrf6t5lmg: ${{ steps.run.outputs.xehrf6t5lmg }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xchkgycsivv: ${{ secrets.xrecw4v2j5j }}
          xvyp42dr72k: ${{ secrets.xaqnb4spokw }}
          xszotgv4ip5: ${{ secrets.xkz7gzyz75s }}
          xjvh6hrq6ho: xvdp7bdfrnz
          xbtsnkhpgcb: xehrf6t5lmg
          xp2jhhej2dn: ${{ needs.xt4jcw5tofl.outputs.x5hwd6xg2qe }}
          xzxr5qsol6j: ${{ secrets.x2tog4huplt }}
          x3kuchgpu5q: ${{ secrets.xquqiaiupja }}
          xojbojpm6qb: ${{ secrets.xzeifyyht7x }}
          x5p326pvqs3: ${{ secrets.xbucws5r6z7 }}
          x4g2hmsuysm: ${{ secrets.xhzquij5vjz }}
          xjj7icmcdxb: ${{ secrets.x62mffq6fec }}
          xi37thjn5hb: ${{ secrets.xhnuatecbvz }}
          xgp36hyshde: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xxlb6nmulgi
  xqu4yhmqapb:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x47zqhb2snl
      - xee755g3umz
      - xzo62xy2scr
      - xt4jcw5tofl
    outputs:
      xk2iquury5t: ${{ steps.run.outputs.xk2iquury5t }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xchkgycsivv: ${{ secrets.xrecw4v2j5j }}
          xvyp42dr72k: ${{ secrets.xaqnb4spokw }}
          xszotgv4ip5: ${{ secrets.xkz7gzyz75s }}
          xjvh6hrq6ho: xo7bfpqgcmu
          xbtsnkhpgcb: xk2iquury5t
          xre7joar3wu: ${{ needs.xt4jcw5tofl.outputs.x5hwd6xg2qe }}
          xzxr5qsol6j: ${{ secrets.x2tog4huplt }}
          x3kuchgpu5q: ${{ secrets.xquqiaiupja }}
          xojbojpm6qb: ${{ secrets.xzeifyyht7x }}
          x5p326pvqs3: ${{ secrets.xbucws5r6z7 }}
          x4g2hmsuysm: ${{ secrets.xhzquij5vjz }}
          xjj7icmcdxb: ${{ secrets.x62mffq6fec }}
          xi37thjn5hb: ${{ secrets.xhnuatecbvz }}
          xgp36hyshde: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xxlb6nmulgi
  xmcfdwihtrx:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x47zqhb2snl
      - xee755g3umz
      - xzo62xy2scr
      - xt4jcw5tofl
    outputs:
      xn5qjlmecvg: ${{ steps.run.outputs.xn5qjlmecvg }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xchkgycsivv: ${{ secrets.xrecw4v2j5j }}
          xvyp42dr72k: ${{ secrets.xaqnb4spokw }}
          xszotgv4ip5: ${{ secrets.xkz7gzyz75s }}
          xjvh6hrq6ho: x6ktxw5sbus
          xbtsnkhpgcb: xn5qjlmecvg
          xaj3boil5af: ${{ needs.xt4jcw5tofl.outputs.x5hwd6xg2qe }}
          xzxr5qsol6j: ${{ secrets.x2tog4huplt }}
          x3kuchgpu5q: ${{ secrets.xquqiaiupja }}
          xojbojpm6qb: ${{ secrets.xzeifyyht7x }}
          x5p326pvqs3: ${{ secrets.xbucws5r6z7 }}
          x4g2hmsuysm: ${{ secrets.xhzquij5vjz }}
          xjj7icmcdxb: ${{ secrets.x62mffq6fec }}
          xi37thjn5hb: ${{ secrets.xhnuatecbvz }}
          xgp36hyshde: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xxlb6nmulgi
  xmmo4p4ynni:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x47zqhb2snl
      - xee755g3umz
      - xzo62xy2scr
      - xt4jcw5tofl
    outputs:
      xrgm2nddmza: ${{ steps.run.outputs.xrgm2nddmza }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xchkgycsivv: ${{ secrets.xrecw4v2j5j }}
          xvyp42dr72k: ${{ secrets.xaqnb4spokw }}
          xszotgv4ip5: ${{ secrets.xkz7gzyz75s }}
          xjvh6hrq6ho: xhuajhrgqja
          xbtsnkhpgcb: xrgm2nddmza
          xfeognifhth: ${{ needs.xt4jcw5tofl.outputs.x5hwd6xg2qe }}
          xzxr5qsol6j: ${{ secrets.x2tog4huplt }}
          x3kuchgpu5q: ${{ secrets.xquqiaiupja }}
          xojbojpm6qb: ${{ secrets.xzeifyyht7x }}
          x5p326pvqs3: ${{ secrets.xbucws5r6z7 }}
          x4g2hmsuysm: ${{ secrets.xhzquij5vjz }}
          xjj7icmcdxb: ${{ secrets.x62mffq6fec }}
          xi37thjn5hb: ${{ secrets.xhnuatecbvz }}
          xgp36hyshde: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xxlb6nmulgi
  xpp33ggxxmi:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - x47zqhb2snl
      - xee755g3umz
      - xzo62xy2scr
      - xt4jcw5tofl
    outputs:
      xd23gqewgdf: ${{ steps.run.outputs.xd23gqewgdf }}
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xchkgycsivv: ${{ secrets.xrecw4v2j5j }}
          xvyp42dr72k: ${{ secrets.xaqnb4spokw }}
          xszotgv4ip5: ${{ secrets.xkz7gzyz75s }}
          xjvh6hrq6ho: xz2erdkuvfl
          xbtsnkhpgcb: xd23gqewgdf
          xeq3b6lhtly: ${{ needs.xt4jcw5tofl.outputs.x5hwd6xg2qe }}
          xzxr5qsol6j: ${{ secrets.x2tog4huplt }}
          x3kuchgpu5q: ${{ secrets.xquqiaiupja }}
          xojbojpm6qb: ${{ secrets.xzeifyyht7x }}
          x5p326pvqs3: ${{ secrets.xbucws5r6z7 }}
          x4g2hmsuysm: ${{ secrets.xhzquij5vjz }}
          xjj7icmcdxb: ${{ secrets.x62mffq6fec }}
          xi37thjn5hb: ${{ secrets.xhnuatecbvz }}
          xgp36hyshde: ${{ secrets.xwfcb4ka6lh }}
        run: ./.github/bin/xxlb6nmulgi
  xxyjrbqojtu:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    needs:
      - xtodkjhlfaf
      - xqu4yhmqapb
      - xmcfdwihtrx
      - xmmo4p4ynni
      - xpp33ggxxmi
      - xt4jcw5tofl
    steps:
      - id: setup
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        env:
          xchkgycsivv: ${{ secrets.xrecw4v2j5j }}
          xvyp42dr72k: ${{ secrets.xaqnb4spokw }}
          xszotgv4ip5: ${{ secrets.xkz7gzyz75s }}
          xjvh6hrq6ho: xqtq6rbukgm
          xbtsnkhpgcb: ''
          x6qolu7k7pg: ${{ needs.xpp33ggxxmi.outputs.xd23gqewgdf }}
          xdwzekw62yc: ${{ needs.xtodkjhlfaf.outputs.xehrf6t5lmg }}
          xjab5i4llo7: ${{ needs.xqu4yhmqapb.outputs.xk2iquury5t }}
          xl7muo5iy6d: ${{ needs.xmcfdwihtrx.outputs.xn5qjlmecvg }}
          xlv2zdufz5a: ${{ needs.xmmo4p4ynni.outputs.xrgm2nddmza }}
          xvocclvrqts: ${{ needs.xt4jcw5tofl.outputs.x5hwd6xg2qe }}
          x3kuchgpu5q: ${{ secrets.xquqiaiupja }}
          xojbojpm6qb: ${{ secrets.xzeifyyht7x }}
          x5p326pvqs3: ${{ secrets.xbucws5r6z7 }}
          x4g2hmsuysm: ${{ secrets.xhzquij5vjz }}
        run: ./.github/bin/xxlb6nmulgi
concurrency:
  group: xxlb6nmulgi
  cancel-in-progress: false
